### ISSUE TITLE
5530 Fiber and 8.0

### ISSUE THREAD

**Issue by yellowhat** [pdreker/fritz_exporter#400]
Hi,
Recently I updated both my router to 8.0:

* FRITZ!Box 7530 AX
* FRITZ!Box 5530 Fiber

After the update I am able to scrape only 7530 AX:

```console
$ podman run -it --rm \
    -e FRITZ_USERNAME="<user>" \
    -e FRITZ_PASSWORD="<pass>" \
    -e FRITZ_HOSTNAME="192.168.0.1" \
    -p 9787:9787 \
    docker.io/pdreker/fritz_exporter:2.5.0
2024-11-09 19:24:19,547     INFO fritzexporter.fritzdevice | Connection to 192.168.0.1 successful, reading capabilities
2024-11-09 19:24:21,060     INFO fritzexporter.fritzdevice | Reading capabilities for 192.168.0.1, got serial 50E6363923BB, model name FRITZ!Box 7530 AX completed
2024-11-09 19:24:21,060     INFO fritzexporter | registering 192.168.0.1 to collector
2024-11-09 19:24:22,406     INFO fritzexporter | Starting listener at 0.0.0.0:9787
2024-11-09 19:24:22,407     INFO fritzexporter | Entering async main loop - exporter is ready
```

And not the 5530 Fiber:

```
$ podman run -it --rm \
    -e FRITZ_HOSTNAME="192.168.0.45" \
    -e FRITZ_USERNAME="<user>" \
    -e FRITZ_PASSWORD="<pass>" \
    -p 9787:9787 \
    docker.io/pdreker/fritz_exporter:2.5.0 # --donate-data
2024-11-09 19:25:51,855     INFO fritzexporter.fritzdevice | Connection to 192.168.0.45 successful, reading capabilities
2024-11-09 19:25:52,253  WARNING fritzexporter.fritzcapability | disabling metrics at service WANPPPConnection1, action GetStatusInfo - fritzconnection.call_action returned UPnPError: 
errorCode: 401
errorDescription: Invalid Action
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/local/lib/python3.12/site-packages/fritzexporter/__main__.py", line 133, in <module>
    main()
  File "/usr/local/lib/python3.12/site-packages/fritzexporter/__main__.py", line 99, in main
    fritz_device = FritzDevice(
                   ^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/fritzexporter/fritzdevice.py", line 53, in __init__
    self.capabilities = FritzCapabilities(self)
                        ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/fritzexporter/fritzcapabilities.py", line 112, in __init__
    self.check_present(device)
  File "/usr/local/lib/python3.12/site-packages/fritzexporter/fritzcapabilities.py", line 137, in check_present
    self.capabilities[c].check_capability(device)
  File "/usr/local/lib/python3.12/site-packages/fritzexporter/fritzcapabilities.py", line 61, in check_capability
    device.fc.call_action(svc, action)
  File "/usr/local/lib/python3.12/site-packages/fritzconnection/core/fritzconnection.py", line 456, in call_action
    return self.soaper.execute(service, action_name, arguments)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/fritzconnection/core/soaper.py", line 286, in execute
    return handle_response(response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/fritzconnection/core/soaper.py", line 268, in handle_response
    raise_fritzconnection_error(response)
  File "/usr/local/lib/python3.12/site-packages/fritzconnection/core/soaper.py", line 191, in raise_fritzconnection_error
    raise exception(message)
fritzconnection.core.exceptions.FritzConnectionException: UPnPError: 
errorCode: 403
errorDescription: Not available Action
```

From the UI: `Home Network` > `Network` > `Network Settings`:
* [x] `Permit access for apps`
* [x] `Transmit status information over UPnP`

Any suggestions?

Thanks

**Comment by pdreker** [comment]
I have recently gotten fiber myself, but haven't had a chance to look into it. I would assume, that the fiber boxes respond differently to se requests, and the code doesn't like that.

I'll have a look!

**Comment by pdreker** [comment]
Could you please run the exporter in with DEBUG log_level, by setting FRITZ_LOG_LEVEL to "DEBUG" (so add `-e FRITZ_LOG_LEVEL=DEBUG` to your podman command) and provide the output? This may get long, so you might want to use a gist, instead of pasting everything here (see https://gist.github.com/ - make sure you redact private information as gists are public).

Some capability check on your box is returning an unexpected result (UPnPError: 401) - which should mean "Forbidden", i.e. access to that resource is restricted, which should not happen - at least not normally.

**Comment by pdreker** [comment]
Sooooo... I could have spotted this without the debug logs, but sometimes one just needs the extra text, to make the connection ;-)

I have just pushed a new develop image, which should catch the error and disable the affected metric. If you could run the exporter using the `docker.io/pdreker/fritz_exporter:develop` image (instead of 2.5.0 - again with DEBUG) it should now work (or at least get further along). You should see, that after the last line before the exception it should log that it disabled a metric. I would be interested in those logs, too.

Please report back, if the exporter now runs with develop and if so, I will release 2.5.1 shortly.

**Comment by yellowhat** [comment]
Sure:

```
podman run -it --rm \
    -e FRITZ_HOSTNAME="192.168.0.45" \
    -e FRITZ_USERNAME="<user>" \
    -e FRITZ_PASSWORD="<pass>" \
    -e FRITZ_LOG_LEVEL=DEBUG \
    -p 9787:9787 \
    docker.io/pdreker/fritz_exporter:develop

2024-11-12 08:09:31,779     INFO fritzexporter.fritzdevice | Connection to 192.168.0.45 successful, reading capabilities
2024-11-12 08:09:31,779    DEBUG fritzexporter.fritzcapability | Capability DeviceInfo set to True on device 192.168.0.45
2024-11-12 08:09:31,939    DEBUG fritzexporter.fritzcapability | Capability HostNumberOfEntries set to True on device 192.168.0.45
2024-11-12 08:09:32,013    DEBUG fritzexporter.fritzcapability | Capability UserInterface set to True on device 192.168.0.45
2024-11-12 08:09:32,075    DEBUG fritzexporter.fritzcapability | Capability LanInterfaceConfig set to True on device 192.168.0.45
2024-11-12 08:09:32,118    DEBUG fritzexporter.fritzcapability | Capability LanInterfaceConfigStatistics set to True on device 192.168.0.45
2024-11-12 08:09:32,171    DEBUG fritzexporter.fritzcapability | Capability WanDSLInterfaceConfig set to False on device 192.168.0.45
2024-11-12 08:09:32,171    DEBUG fritzexporter.fritzcapability | Capability WanDSLInterfaceConfigAVM set to False on device 192.168.0.45
2024-11-12 08:09:32,172    DEBUG fritzexporter.fritzcapability | Capability WanPPPConnectionStatus set to True on device 192.168.0.45
2024-11-12 08:09:32,214  WARNING fritzexporter.fritzcapability | disabling metrics at service WANPPPConnection1, action GetStatusInfo - fritzconnection.call_action returned UPnPError: 
errorCode: 401
errorDescription: Invalid Action
2024-11-12 08:09:32,214    DEBUG fritzexporter.fritzcapability | Capability WanCommonInterfaceConfig set to True on device 192.168.0.45
2024-11-12 08:09:32,243    DEBUG fritzexporter.fritzcapability | Capability WanCommonInterfaceDataBytes set to True on device 192.168.0.45
2024-11-12 08:09:32,356    DEBUG fritzexporter.fritzcapability | Capability WanCommonInterfaceByteRate set to True on device 192.168.0.45
2024-11-12 08:09:32,403  WARNING fritzexporter.fritzcapability | disabling metrics at service WANCommonIFC1, action GetAddonInfos - fritzconnection.call_action returned UPnPError: 
errorCode: 403
errorDescription: Not available Action
2024-11-12 08:09:32,403    DEBUG fritzexporter.fritzcapability | Capability WanCommonInterfaceDataPackets set to True on device 192.168.0.45
2024-11-12 08:09:32,500    DEBUG fritzexporter.fritzcapability | Capability WlanConfigurationInfo checking WLANConfiguration1 on 192.168.0.45
2024-11-12 08:09:32,500    DEBUG fritzexporter.fritzcapability | Capability WlanConfigurationInfo in WLAN 1 set to True on device 192.168.0.45
2024-11-12 08:09:32,762    DEBUG fritzexporter.fritzcapability | Capability WlanConfigurationInfo checking WLANConfiguration2 on 192.168.0.45
2024-11-12 08:09:32,762    DEBUG fritzexporter.fritzcapability | Capability WlanConfigurationInfo in WLAN 2 set to True on device 192.168.0.45
2024-11-12 08:09:32,984    DEBUG fritzexporter.fritzcapability | Capability WlanConfigurationInfo checking WLANConfiguration3 on 192.168.0.45
2024-11-12 08:09:32,984    DEBUG fritzexporter.fritzcapability | Capability WlanConfigurationInfo in WLAN 3 set to True on device 192.168.0.45
2024-11-12 08:09:33,256    DEBUG fritzexporter.fritzcapability | Capability WlanConfigurationInfo checking WLANConfiguration4 on 192.168.0.45
2024-11-12 08:09:33,256    DEBUG fritzexporter.fritzcapability | Capability WlanConfigurationInfo in WLAN 4 set to False on device 192.168.0.45
2024-11-12 08:09:33,256    DEBUG fritzexporter.fritzcapability | Capability HostInfo set to False on device 192.168.0.45
2024-11-12 08:09:33,256    DEBUG fritzexporter.fritzcapability | Capability HomeAutomation set to True on device 192.168.0.45
2024-11-12 08:09:33,357     INFO fritzexporter.fritzdevice | Reading capabilities for 192.168.0.45, got serial <serial>, model name FRITZ!Box 5530 Fiber completed
2024-11-12 08:09:33,357     INFO fritzexporter | registering 192.168.0.45 to collector
2024-11-12 08:09:33,357    DEBUG fritzexporter.fritzdevice | registered device 192.168.0.45 (FRITZ!Box 5530 Fiber) to collector
2024-11-12 08:09:33,357    DEBUG fritzexporter.fritzcapability | Fetching DeviceInfo metrics for 192.168.0.45: True
2024-11-12 08:09:33,423    DEBUG fritzexporter.fritzcapability | Fetching HostNumberOfEntries metrics for 192.168.0.45: True
2024-11-12 08:09:33,465    DEBUG fritzexporter.fritzcapability | Fetching UserInterface metrics for 192.168.0.45: True
2024-11-12 08:09:33,563    DEBUG fritzexporter.fritzcapability | Fetching LanInterfaceConfig metrics for 192.168.0.45: True
2024-11-12 08:09:33,580    DEBUG fritzexporter.fritzcapability | Fetching LanInterfaceConfigStatistics metrics for 192.168.0.45: True
2024-11-12 08:09:33,636    DEBUG fritzexporter.fritzcapability | Fetching WanDSLInterfaceConfig metrics for 192.168.0.45: False
2024-11-12 08:09:33,636    DEBUG fritzexporter.fritzcapability | Fetching WanDSLInterfaceConfigAVM metrics for 192.168.0.45: False
2024-11-12 08:09:33,636    DEBUG fritzexporter.fritzcapability | Fetching WanPPPConnectionStatus metrics for 192.168.0.45: False
2024-11-12 08:09:33,636    DEBUG fritzexporter.fritzcapability | Fetching WanCommonInterfaceConfig metrics for 192.168.0.45: True
2024-11-12 08:09:33,695    DEBUG fritzexporter.fritzcapability | Fetching WanCommonInterfaceDataBytes metrics for 192.168.0.45: True
2024-11-12 08:09:33,806    DEBUG fritzexporter.fritzcapability | Fetching WanCommonInterfaceByteRate metrics for 192.168.0.45: False
2024-11-12 08:09:33,806    DEBUG fritzexporter.fritzcapability | Fetching WanCommonInterfaceDataPackets metrics for 192.168.0.45: True
2024-11-12 08:09:33,923    DEBUG fritzexporter.fritzcapability | Fetching WlanConfigurationInfo metrics for 192.168.0.45: True
2024-11-12 08:09:33,923    DEBUG fritzexporter.fritzcapability | WLANConfigurationInfo._generateMetricValues called: 192.168.0.45 - WlanConfigurationInfo
2024-11-12 08:09:33,923    DEBUG fritzexporter.fritzcapability | WLANConfigurationInfo._generateMetricValues checking WLAN 0 (enabled: True) on 192.168.0.45
2024-11-12 08:09:33,923    DEBUG fritzexporter.fritzcapability | WLANCapability._generateMetricValues fetching metrics for 192.168.0.45: 0
2024-11-12 08:09:34,168    DEBUG fritzexporter.fritzcapability | WLANConfigurationInfo._generateMetricValues checking WLAN 1 (enabled: True) on 192.168.0.45
2024-11-12 08:09:34,168    DEBUG fritzexporter.fritzcapability | WLANCapability._generateMetricValues fetching metrics for 192.168.0.45: 1
2024-11-12 08:09:34,407    DEBUG fritzexporter.fritzcapability | WLANConfigurationInfo._generateMetricValues checking WLAN 2 (enabled: True) on 192.168.0.45
2024-11-12 08:09:34,407    DEBUG fritzexporter.fritzcapability | WLANCapability._generateMetricValues fetching metrics for 192.168.0.45: 2
2024-11-12 08:09:34,655    DEBUG fritzexporter.fritzcapability | WLANConfigurationInfo._generateMetricValues checking WLAN 3 (enabled: False) on 192.168.0.45
2024-11-12 08:09:34,655    DEBUG fritzexporter.fritzcapability | Fetching HostInfo metrics for 192.168.0.45: False
2024-11-12 08:09:34,655    DEBUG fritzexporter.fritzcapability | Fetching HomeAutomation metrics for 192.168.0.45: True
2024-11-12 08:09:34,655    DEBUG fritzexporter.fritzcapability | Fetching home automation device information for index 0
2024-11-12 08:09:34,818    DEBUG fritzexporter.fritzcapability | Got IndexError for index 0, stopping
2024-11-12 08:09:34,818     INFO fritzexporter | Starting listener at 0.0.0.0:9787
2024-11-12 08:09:34,819     INFO fritzexporter | Entering async main loop - exporter is ready
```

**Comment by pdreker** [comment]
OK, so I double checked this against my 5590 Fiber an my box reports the WanComminInterfaceByteRateMetrics just fine (Capability is True after checks) and the box reports the current throughput via these metrics. I have no idea, why the 5530 wouldn't do this (it's just a byte/s gauge, after all),but at least the error is gone.

I will release 2.5.1 with no further changes from develop right now.
