### ISSUE TITLE
Crash at start: 606 -  Action Not Authorized

### ISSUE THREAD

**Issue by chevdor** [pdreker/fritz_exporter#63]
I am using the latest published docker version and a 6660 (cable).
From the logs, it seems that the connection is properly established but it breaks right after.

```
LOG LEVEL READ FROM CONFIG
2021-09-02 20:11:10,168     INFO fritzexporter | registering 192.168.178.1 to collector
2021-09-02 20:11:10,984     INFO fritzexporter.fritzdevice | Connection to 192.168.178.1 successful, reading capabilities
2021-09-02 20:11:10,984    DEBUG fritzexporter.fritzcapability | Capability DeviceInfo set to {self.present} on device {device.host}
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/app/fritzexporter/__main__.py", line 74, in <module>
    main()
  File "/app/fritzexporter/__main__.py", line 58, in main
    FritzDevice(dev['hostname'], dev['username'], dev['password'], dev['name']))
  File "/app/fritzexporter/fritzdevice.py", line 35, in __init__
    self.capabilities = FritzCapabilities(self)
  File "/app/fritzexporter/fritzcapabilities.py", line 75, in __init__
    self.checkPresent(device)
  File "/app/fritzexporter/fritzcapabilities.py", line 99, in checkPresent
    self.capabilities[c].checkCapability(device)
  File "/app/fritzexporter/fritzcapabilities.py", line 46, in checkCapability
    device.fc.call_action(svc, action)
  File "/usr/local/lib/python3.9/site-packages/fritzconnection/core/fritzconnection.py", line 227, in call_action
    return self.soaper.execute(service, action_name, arguments)
  File "/usr/local/lib/python3.9/site-packages/fritzconnection/core/soaper.py", line 238, in execute
    return handle_response(response)
  File "/usr/local/lib/python3.9/site-packages/fritzconnection/core/soaper.py", line 222, in handle_response
    raise_fritzconnection_error(response)
  File "/usr/local/lib/python3.9/site-packages/fritzconnection/core/soaper.py", line 147, in raise_fritzconnection_error
    raise exception(message)
fritzconnection.core.exceptions.FritzSecurityError: UPnPError: 
errorCode: 606
errorDescription: Action Not Authorized
```

**Comment by chevdor** [comment]
The issue seems to be known and commenting the following goes a little further:
https://github.com/pdreker/fritz_exporter/blob/develop/fritzexporter/fritzcapabilities.py#L43-L51

**Comment by chevdor** [comment]
After commenting the block mentioned above, I can see:

```
LOG LEVEL READ FROM CONFIG
2021-09-02 20:26:32,594     INFO fritzexporter | registering 192.168.178.1 to collector
2021-09-02 20:26:32,916     INFO fritzexporter.fritzdevice | Connection to 192.168.178.1 successful, reading capabilities
2021-09-02 20:26:32,916    DEBUG fritzexporter.fritzcapability | Capability DeviceInfo set to {self.present} on device {device.host}
2021-09-02 20:26:32,916    DEBUG fritzexporter.fritzcapability | Capability HostNumberOfEntries set to {self.present} on device {device.host}
2021-09-02 20:26:32,916    DEBUG fritzexporter.fritzcapability | Capability UserInterface set to {self.present} on device {device.host}
2021-09-02 20:26:32,917    DEBUG fritzexporter.fritzcapability | Capability LanInterfaceConfig set to {self.present} on device {device.host}
2021-09-02 20:26:32,917    DEBUG fritzexporter.fritzcapability | Capability LanInterfaceConfigStatistics set to {self.present} on device {device.host}
2021-09-02 20:26:32,917    DEBUG fritzexporter.fritzcapability | Capability WanDSLInterfaceConfig set to {self.present} on device {device.host}
2021-09-02 20:26:32,917    DEBUG fritzexporter.fritzcapability | Capability WanDSLInterfaceConfigAVM set to {self.present} on device {device.host}
2021-09-02 20:26:32,917    DEBUG fritzexporter.fritzcapability | Capability WanPPPConnectionStatus set to {self.present} on device {device.host}
2021-09-02 20:26:32,917    DEBUG fritzexporter.fritzcapability | Capability WanCommonInterfaceConfig set to {self.present} on device {device.host}
2021-09-02 20:26:32,917    DEBUG fritzexporter.fritzcapability | Capability WanCommonInterfaceDataBytes set to {self.present} on device {device.host}
2021-09-02 20:26:32,917    DEBUG fritzexporter.fritzcapability | Capability WanCommonInterfaceByteRate set to {self.present} on device {device.host}
2021-09-02 20:26:32,917    DEBUG fritzexporter.fritzcapability | Capability WanCommonInterfaceDataPackets set to {self.present} on device {device.host}
2021-09-02 20:26:32,917    DEBUG fritzexporter.fritzcapability | WLANCapability WlanConfigurationInfo checking WLANConfiguration1 on 192.168.178.1
2021-09-02 20:26:32,918    DEBUG fritzexporter.fritzcapability | WLANCapability WlanConfigurationInfo in WLAN 0 set to {self.wifi_present[wlan]} on device {device.host}
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/app/fritzexporter/__main__.py", line 74, in <module>
    main()
  File "/app/fritzexporter/__main__.py", line 58, in main
    FritzDevice(dev['hostname'], dev['username'], dev['password'], dev['name']))
  File "/app/fritzexporter/fritzdevice.py", line 35, in __init__
    self.capabilities = FritzCapabilities(self)
  File "/app/fritzexporter/fritzcapabilities.py", line 75, in __init__
    self.checkPresent(device)
  File "/app/fritzexporter/fritzcapabilities.py", line 99, in checkPresent
    self.capabilities[c].checkCapability(device)
  File "/app/fritzexporter/fritzcapabilities.py", line 470, in checkCapability
    device.fc.call_action(svc, action)
  File "/usr/local/lib/python3.9/site-packages/fritzconnection/core/fritzconnection.py", line 227, in call_action
    return self.soaper.execute(service, action_name, arguments)
  File "/usr/local/lib/python3.9/site-packages/fritzconnection/core/soaper.py", line 238, in execute
    return handle_response(response)
  File "/usr/local/lib/python3.9/site-packages/fritzconnection/core/soaper.py", line 222, in handle_response
    raise_fritzconnection_error(response)
  File "/usr/local/lib/python3.9/site-packages/fritzconnection/core/soaper.py", line 147, in raise_fritzconnection_error
    raise exception(message)
fritzconnection.core.exceptions.FritzSecurityError: UPnPError: 
errorCode: 606
errorDescription: Action Not Authorized
```

**Comment by chevdor** [comment]
I could get the exporter to start but I did cut quite hard with the following patch:
```
diff --git a/.gitignore b/.gitignore
index 3643ce9..523125e 100644
--- a/.gitignore
+++ b/.gitignore
@@ -148,3 +148,5 @@ cython_debug/
 
 # Local History for Visual Studio Code
 .history/
+
+/*.yml
\ No newline at end of file
diff --git a/fritzexporter/fritzcapabilities.py b/fritzexporter/fritzcapabilities.py
index 2d1d864..c94ce15 100644
--- a/fritzexporter/fritzcapabilities.py
+++ b/fritzexporter/fritzcapabilities.py
@@ -44,10 +44,12 @@ class FritzCapability(ABC):
             for (svc, action) in self.requirements:
                 try:
                     device.fc.call_action(svc, action)
-                except (ServiceError, ActionError, FritzInternalError) as e:
+                except:
                     logger.warn(
-                        f'disabling metrics at service {svc}, action {action} - '
-                        f'fritzconnection.call_action returned {str(e)}')
+                        f'disabling metrics at service {svc}, action {action}')
+                    # logger.warn(
+                    #     f'disabling metrics at service {svc}, action {action} - '
+                    #     f'fritzconnection.call_action returned {str(e)}')
                     self.present = False
 
     def getMetrics(self, devices, name):
@@ -468,10 +470,9 @@ class WlanConfigurationInfo(FritzCapability):
                 for (svc, action) in requirements:
                     try:
                         device.fc.call_action(svc, action)
-                    except (ServiceError, ActionError, FritzInternalError) as e:
+                    except:
                         logger.warn(
-                            f'disabling metrics at service {svc}, action {action} - '
-                            f'fritzconnection.call_action returned {e}')
+                            f'disabling metrics at service {svc}, action {action}')
                         self.wifi_present[wlan - 1] = False
         self.present = any(self.wifi_present)
 
@@ -505,7 +506,9 @@ class WlanConfigurationInfo(FritzCapability):
             logger.debug(
                 'WLANConfigurationInfo._getMetricValues checking WLAN '
                 f'{index} (enabled: {wlan}) on {device.host}')
+            wlan = False
             if wlan:
+
                 logger.debug(
                     f'WLANCapability._getMetrics fetching metrics for {device.host}: {index}')
                 wlan_result = device.fc.call_action(f'WLANConfiguration{index+1}', 'GetInfo')
diff --git a/fritzexporter/fritzdevice.py b/fritzexporter/fritzdevice.py
index f82cde9..a9e9b0d 100644
--- a/fritzexporter/fritzdevice.py
+++ b/fritzexporter/fritzdevice.py
@@ -48,7 +48,7 @@ class FritzDevice():
             self.serial = device_info['NewSerialNumber']
             self.model = device_info['NewModelName']
 
-        except (FritzServiceError, FritzActionError):
+        except:
             logger.exception(
                 f'Fritz Device {self.host} does not provide basic device '
                 'info (Service: DeviceInfo1, Action: GetInfo).'
```

So the first issue is that you don't catch the `fritzconnection.core.exceptions.FritzSecurityError` exception and those seems to occure quite a lot.

Finally, I convinced the exporter that my fritzbox has no WLAN which is def. not a solution but I wanted to see what was on the way.

**Comment by chevdor** [comment]
Ah ah!
The issue comes from using the a **non admin** account (which should be recommended...).
Using the admin account, all the issue mentioned above vanish.

**Comment by chevdor** [comment]
The user does not need to be admin but needs the `FRITZ!Box Settings` rights.

**Comment by chevdor** [comment]
I am closing this issue hoping the doc may help others running in similar issues.
It does make sense to need those rights. An improvement could be to run a quick test at start and if it throws a `FritzSecurityError`, we could hint the user about the required rights.
