### ISSUE TITLE
Invalid Args Error with uncommented HostInfo

### ISSUE THREAD

**Issue by DaHoert** [pdreker/fritz_exporter#69]
Hello there,

I'm trying to get the exporter running with detailed HostInfo but am getting the following error:

```
fritz-exporter    | 2022-03-17 19:49:39,415    DEBUG fritzexporter.fritzcapability | Capability HostInfo set to {self.present} on device {device.host}
fritz-exporter    | Traceback (most recent call last):
fritz-exporter    |   File "/usr/local/lib/python3.9/runpy.py", line 197, in _run_module_as_main
fritz-exporter    |     return _run_code(code, main_globals, None,
fritz-exporter    |   File "/usr/local/lib/python3.9/runpy.py", line 87, in _run_code
fritz-exporter    |     exec(code, run_globals)
fritz-exporter    |   File "/app/fritzexporter/__main__.py", line 74, in <module>
fritz-exporter    |     main()
fritz-exporter    |   File "/app/fritzexporter/__main__.py", line 58, in main
fritz-exporter    |     FritzDevice(dev['hostname'], dev['username'], dev['password'], dev['name']))
fritz-exporter    |   File "/app/fritzexporter/fritzdevice.py", line 35, in __init__
fritz-exporter    |     self.capabilities = FritzCapabilities(self)
fritz-exporter    |   File "/app/fritzexporter/fritzcapabilities.py", line 75, in __init__
fritz-exporter    |     self.checkPresent(device)
fritz-exporter    |   File "/app/fritzexporter/fritzcapabilities.py", line 99, in checkPresent
fritz-exporter    |     self.capabilities[c].checkCapability(device)
fritz-exporter    |   File "/app/fritzexporter/fritzcapabilities.py", line 46, in checkCapability
fritz-exporter    |     device.fc.call_action(svc, action)
fritz-exporter    |   File "/usr/local/lib/python3.9/site-packages/fritzconnection/core/fritzconnection.py", line 227, in call_action
fritz-exporter    |     return self.soaper.execute(service, action_name, arguments)
fritz-exporter    |   File "/usr/local/lib/python3.9/site-packages/fritzconnection/core/soaper.py", line 238, in execute
fritz-exporter    |     return handle_response(response)
fritz-exporter    |   File "/usr/local/lib/python3.9/site-packages/fritzconnection/core/soaper.py", line 222, in handle_response
fritz-exporter    |     raise_fritzconnection_error(response)
fritz-exporter    |   File "/usr/local/lib/python3.9/site-packages/fritzconnection/core/soaper.py", line 147, in raise_fritzconnection_error
fritz-exporter    |     raise exception(message)
fritz-exporter    | fritzconnection.core.exceptions.FritzArgumentError: UPnPError: 
fritz-exporter    | errorCode: 402
fritz-exporter    | errorDescription: Invalid Args
fritz-exporter    | LOG LEVEL READ FROM CONFIG
```

without the "HostInfo" Class everything is running fine.

any help would be appreciated :)

**Comment by pdreker** [comment]
Hi,

the HostInfo Code is pretty much untested, except for running it against my 7590 with OS 7.25, so problems are not quite unexpected.

I'll see, if it still works against my 7590 with current OS version.

In the meantime: What Model of Fritz!Box do you use and which version of Fritz!OS is on there?

**Comment by DaHoert** [comment]
Hi Patrick, thx for the reply.

At the moment I got a Fritz!Box 7530 with latest Fritz!OS 7.29 and a Fritz!Repeater 1750E also with Fritz!OS 7.29. 

My guess is that it has probably to do with the newer Version which might report new or other capabilities or something like that.

**Comment by pdreker** [comment]
I have looked into this, and an unrelated change in the past has rendered the HostIInfo Code unusable in the current form.

Basically in https://github.com/pdreker/fritz_exporter/commit/007f04e28703f0643d3bc2e8e494bacd7fdbb0f7#diff-bd15587103d98db86e65d105d3e89f8d4e50aba86decfc3077076b4d720ca4f6R27 I call every reported capability from the box, to test if it really works. Unfortunately the HostInfo actions require arguments, which the code does not provide, thus the box reports "Bad Arguments" back, which is entirely correct.

I will try to come up with a fix.

**Comment by pdreker** [comment]
I have just pushed version 2.1.0 which addresses the HostInfo issue.
